kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexentastor5-nfs-wip
  annotations:
    volume.beta.kubernetes.io/storage-class: "nexentastor5-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
