kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1alpha1
metadata:
  name: run-nexentastor5-provisioner
subjects:
  - kind: ServiceAccount
    name: nexentastor5-provisioner
    namespace: default
roleRef:
  kind: ClusterRole
  name: nexentastor5-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
