kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nexentastor5-nfs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nexentastor5-nfs-provisioner
    spec:
      containers:
        - name: nexentastor5-nfs-provisioner
          image:  quay.io/alexey_khodos/nexentastor5-nfs-provisioner
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: src
              mountPath: /mnt
          env:
            - name: NEXENTA_HOSTNAME
              value: 10.3.199.29
            - name: NEXENTA_HOSTPORT
              value: "8443"
            - name: NEXENTA_PASSWORD
              value: "nexenta1"
            - name: NEXENTA_USERNAME
              value: "admin"
            - name: NEXENTA_HOSTPOOL
              value: QA
            - name: PARENT_FILESYSTEM
              value: "kubernetes"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
