kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nexentastor5-nfs-provisioner-wip
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nexentastor5-nfs-provisioner-wip
    spec:
      containers:
        - name: nexentastor5-nfs-provisioner-wip
          image:  quay.io/alexey_khodos/nexentastor5-nfs-provisioner:wip
          imagePullPolicy: "Always"
          env:
            - name: NEXENTA_HOSTNAME
              value: 10.3.199.29
            - name: NEXENTA_HOSTPORT
              value: "8443"
            - name: NEXENTA_PASSWORD
              value: "nexenta1"
            - name: NEXENTA_USERNAME
              value: "admin"
            - name: NEXENTA_POOL
              value: QA
            - name: NEXENTA_PARENT_FILESYSTEM
              value: "kubernetes"
            - name: IGNORE_SSL_CERTIFICATES
              value: "true"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
