FROM golang:1.8.3-alpine3.6

RUN apk update && apk add git

RUN go get -v github.com/kubernetes-incubator/external-storage/...; exit 0
WORKDIR "/go/src/github.com/kubernetes-incubator/external-storage/"
RUN git checkout 8aeb2d0
RUN git clone https://github.com/nexenta/k8s-nexentastor5-nfs
WORKDIR "/go/src/github.com/kubernetes-incubator/external-storage/k8s-nexentastor5-nfs"
RUN git checkout $BRANCH
RUN go build nexentastor5-nfs-provisioner.go
RUN cp nexentastor5-nfs-provisioner /go/bin/
